# config/config.yaml

window_size: 4
step_size: 4
model: 'SVML'
models_to_run:
  - 'AHL'  # Always Hot
  - 'AWL'  # Always Warm
  - 'SVMR'
  - 'ONL'
  - 'LR'
pop_name: 'Pop2'

# User Profile Configuration
profile:
  cost_weight: 20  # Value between 1-99, latency_weight will be (100 - cost_weight)