# config/config.yaml

window_size: 4
step_size: 4
model: 'SVML'
models_to_run:
  - 'AHL'  # Always Hot
  - 'AWL'  # Always Warm
  - 'SVMR'
  - 'ONL'
  - 'SVML'
  - 'RF'
  - 'DCT'
  - 'KNN'
  - 'LR'
pop_name: 'Pop2'
