# config/config.yaml

window_size: 4
step_size: 4
model: 'SVML'
models_to_run:
  - 'AHL'  # Always Hot
  - 'AWL'  # Always Warm
  - 'ONL'  # Online
  - 'SVMR' # SVM with RBF kernel
  - 'SVML' # SVM with Linear kernel
  - 'RF'   # Random Forest
  - 'DCT'  # Decision Tree
  - 'KNN'  # K-Nearest Neighbors
  - 'LR'   # Logistic Regression
  - 'GBC'  # Gradient Boosting
  - 'ABC'  # AdaBoost
  - 'ETC'  # Extra Trees
  - 'MLP'  # Neural Network
  - 'XGB'  # XGBoost
  - 'LGBM' # LightGBM
pop_name: 'Pop2'
